package delivery

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/akandalintsev/go-tests-layout/internal/services/store.Store -o ./internal/services/store/store_mock.go -n StoreMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// StoreMock implements Store
type StoreMock struct {
	t minimock.Tester

	funcStocks          func(ids []string) (pa1 []ProductStock, err error)
	inspectFuncStocks   func(ids []string)
	afterStocksCounter  uint64
	beforeStocksCounter uint64
	StocksMock          mStoreMockStocks
}

// NewStoreMock returns a mock for Store
func NewStoreMock(t minimock.Tester) *StoreMock {
	m := &StoreMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.StocksMock = mStoreMockStocks{mock: m}
	m.StocksMock.callArgs = []*StoreMockStocksParams{}

	return m
}

type mStoreMockStocks struct {
	mock               *StoreMock
	defaultExpectation *StoreMockStocksExpectation
	expectations       []*StoreMockStocksExpectation

	callArgs []*StoreMockStocksParams
	mutex    sync.RWMutex
}

// StoreMockStocksExpectation specifies expectation struct of the Store.Stocks
type StoreMockStocksExpectation struct {
	mock    *StoreMock
	params  *StoreMockStocksParams
	results *StoreMockStocksResults
	Counter uint64
}

// StoreMockStocksParams contains parameters of the Store.Stocks
type StoreMockStocksParams struct {
	ids []string
}

// StoreMockStocksResults contains results of the Store.Stocks
type StoreMockStocksResults struct {
	pa1 []ProductStock
	err error
}

// Expect sets up expected params for Store.Stocks
func (mmStocks *mStoreMockStocks) Expect(ids []string) *mStoreMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("StoreMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &StoreMockStocksExpectation{}
	}

	mmStocks.defaultExpectation.params = &StoreMockStocksParams{ids}
	for _, e := range mmStocks.expectations {
		if minimock.Equal(e.params, mmStocks.defaultExpectation.params) {
			mmStocks.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStocks.defaultExpectation.params)
		}
	}

	return mmStocks
}

// Inspect accepts an inspector function that has same arguments as the Store.Stocks
func (mmStocks *mStoreMockStocks) Inspect(f func(ids []string)) *mStoreMockStocks {
	if mmStocks.mock.inspectFuncStocks != nil {
		mmStocks.mock.t.Fatalf("Inspect function is already set for StoreMock.Stocks")
	}

	mmStocks.mock.inspectFuncStocks = f

	return mmStocks
}

// Return sets up results that will be returned by Store.Stocks
func (mmStocks *mStoreMockStocks) Return(pa1 []ProductStock, err error) *StoreMock {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("StoreMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &StoreMockStocksExpectation{mock: mmStocks.mock}
	}
	mmStocks.defaultExpectation.results = &StoreMockStocksResults{pa1, err}
	return mmStocks.mock
}

//Set uses given function f to mock the Store.Stocks method
func (mmStocks *mStoreMockStocks) Set(f func(ids []string) (pa1 []ProductStock, err error)) *StoreMock {
	if mmStocks.defaultExpectation != nil {
		mmStocks.mock.t.Fatalf("Default expectation is already set for the Store.Stocks method")
	}

	if len(mmStocks.expectations) > 0 {
		mmStocks.mock.t.Fatalf("Some expectations are already set for the Store.Stocks method")
	}

	mmStocks.mock.funcStocks = f
	return mmStocks.mock
}

// When sets expectation for the Store.Stocks which will trigger the result defined by the following
// Then helper
func (mmStocks *mStoreMockStocks) When(ids []string) *StoreMockStocksExpectation {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("StoreMock.Stocks mock is already set by Set")
	}

	expectation := &StoreMockStocksExpectation{
		mock:   mmStocks.mock,
		params: &StoreMockStocksParams{ids},
	}
	mmStocks.expectations = append(mmStocks.expectations, expectation)
	return expectation
}

// Then sets up Store.Stocks return parameters for the expectation previously defined by the When method
func (e *StoreMockStocksExpectation) Then(pa1 []ProductStock, err error) *StoreMock {
	e.results = &StoreMockStocksResults{pa1, err}
	return e.mock
}

// Stocks implements Store
func (mmStocks *StoreMock) Stocks(ids []string) (pa1 []ProductStock, err error) {
	mm_atomic.AddUint64(&mmStocks.beforeStocksCounter, 1)
	defer mm_atomic.AddUint64(&mmStocks.afterStocksCounter, 1)

	if mmStocks.inspectFuncStocks != nil {
		mmStocks.inspectFuncStocks(ids)
	}

	mm_params := &StoreMockStocksParams{ids}

	// Record call args
	mmStocks.StocksMock.mutex.Lock()
	mmStocks.StocksMock.callArgs = append(mmStocks.StocksMock.callArgs, mm_params)
	mmStocks.StocksMock.mutex.Unlock()

	for _, e := range mmStocks.StocksMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pa1, e.results.err
		}
	}

	if mmStocks.StocksMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStocks.StocksMock.defaultExpectation.Counter, 1)
		mm_want := mmStocks.StocksMock.defaultExpectation.params
		mm_got := StoreMockStocksParams{ids}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStocks.t.Errorf("StoreMock.Stocks got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStocks.StocksMock.defaultExpectation.results
		if mm_results == nil {
			mmStocks.t.Fatal("No results are set for the StoreMock.Stocks")
		}
		return (*mm_results).pa1, (*mm_results).err
	}
	if mmStocks.funcStocks != nil {
		return mmStocks.funcStocks(ids)
	}
	mmStocks.t.Fatalf("Unexpected call to StoreMock.Stocks. %v", ids)
	return
}

// StocksAfterCounter returns a count of finished StoreMock.Stocks invocations
func (mmStocks *StoreMock) StocksAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.afterStocksCounter)
}

// StocksBeforeCounter returns a count of StoreMock.Stocks invocations
func (mmStocks *StoreMock) StocksBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.beforeStocksCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Stocks.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStocks *mStoreMockStocks) Calls() []*StoreMockStocksParams {
	mmStocks.mutex.RLock()

	argCopy := make([]*StoreMockStocksParams, len(mmStocks.callArgs))
	copy(argCopy, mmStocks.callArgs)

	mmStocks.mutex.RUnlock()

	return argCopy
}

// MinimockStocksDone returns true if the count of the Stocks invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockStocksDone() bool {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	return true
}

// MinimockStocksInspect logs each unmet expectation
func (m *StoreMock) MinimockStocksInspect() {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Stocks with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		if m.StocksMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StoreMock.Stocks")
		} else {
			m.t.Errorf("Expected call to StoreMock.Stocks with params: %#v", *m.StocksMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		m.t.Error("Expected call to StoreMock.Stocks")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StoreMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockStocksInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockStocksDone()
}
